### ISSUE TITLE
path problem

### ISSUE THREAD

**Issue by erscoder** [maxchehab/remote-linux-unlocker#4]
may 20 17:48:41 argon python[9576]: /usr/bin/python: can't open file '/home/maxchehab/Projects/remote-linux-unlocker/linux-daemon/unlocker-daemon.py': [Errno 2] No such file or directory

**Comment by maxchehab** [comment]
Edit https://github.com/maxchehab/Remote-Linux-Unlocker/blob/master/linux-daemon/unlocker-deamon.service to reflect the path where `unlocker-daemon.py` is resolved.
